name: Deploy to GitHub Pages
on:
  push:
    branches:
      - release-admin
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout ğŸ›ï¸ # æ­¥éª¤å
        uses: actions/checkout@master # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/checkout

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      # step 3. å®‰è£…ä¾èµ–å¹¶æ‰“åŒ…
      - name: Install and Build ğŸ”§
        run: |
          pnpm config set registry https://registry.npmmirror.com
          pnpm build --filter @gbeata/admin-docs

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:anyone-yuren/gbeata-admin-docs.git
          BRANCH: gh-pages
          FOLDER: docs-dist
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
