# 1. ä¸ºå·¥ä½œæµå®šä¹‰åå­—
name: ã€ŒGitHub Pagesã€Build & Deploy

# 2. è§¦å‘æ¡ä»¶ä¿®æ”¹ä¸º: å½“ main æˆ– master åˆ†æ”¯, æœ‰ push çš„æ—¶å€™, æ‰§è¡Œä»»åŠ¡
on:
  push:
    branches:
      - master
      - admin

# 3. åˆ›å»ºå·¥ä½œæµ
jobs:
  build: # å·¥ä½œæµåç§°
    runs-on: ubuntu-latest # ä¾èµ–ç¯å¢ƒ

    steps: # å·¥ä½œæµæ­¥éª¤
      # step 1. è·å–æºç , æ‹‰å–ä»“åº“ä»£ç 
      - name: Chekcout ğŸ›ï¸ # æ­¥éª¤å
        uses: actions/checkout@master # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/checkout

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      # step 3. å®‰è£…ä¾èµ–å¹¶æ‰“åŒ…
      - name: Install and Build ğŸ”§
        run: |
          pnpm config set registry https://registry.npmmirror.com
          pnpm build:admin

      # step 4. é¡¹ç›®éƒ¨ç½², å°†æ‰“åŒ…åçš„äº§ç‰©åˆå¹¶åˆ°æŒ‡å®šçš„åˆ†æ”¯ä¸Š
      - name: Deploy ğŸš€ # æ­¥éª¤å
        uses: JamesIves/github-pages-deploy-action@v4.2.2 # ä½¿ç”¨æ’ä»¶ => https://github.com/JamesIves/github-pages-deploy-action
        with:
          BRANCH: gh-pages # éƒ¨ç½²åˆ†æ”¯
          FOLDER: gbeata-dist # æ‰“åŒ…, é™æ€èµ„æºè¾“å‡ºçš„ç›®å½•

      # step 6. ä½¿ç”¨ changesets æ›´æ–°ç‰ˆæœ¬
      - name: Update Version
        uses: changesets/action@v1
        with:
          version: pnpm change:ver
          commit: "chore: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Read Package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: packagejson

      - name: Debug Package Version
        run: echo "Package version ${{ steps.packagejson.outputs.version }}"

      - name: Create Release for Tag
        uses: actions/create-release@v1
        id: release-tag
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: ${{ steps.packagejson.outputs.version }}
          name: ${{ steps.packagejson.outputs.version }}
          body: ${{ steps.packagejson.outputs.content }}
          draft: false
          prerelease: false
